DECLARE  totalno  NUMBER;
BEGIN  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BBANK_MANAGEMENT_EMPLOYEE';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BBANK_MANAGEMENT_EMPLOYEE CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BBANK_MANAGEMENT_EMPLOYEE
    (BMSEMPLOYEE_ID NUMBER(10,0), 
	EMP_NAME VARCHAR2(40 BYTE), 
	EMP_PHONENO NUMBER(10,0), 
	BLOODBANK_ID NUMBER(10,0)
   )';
    ELSE IF (totalno = 0) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BBANK_MANAGEMENT_EMPLOYEE
    (BMSEMPLOYEE_ID NUMBER(10,0), 
	EMP_NAME VARCHAR2(40 BYTE), 
	EMP_PHONENO NUMBER(10,0), 
	BLOODBANK_ID NUMBER(10,0)
   )';
END IF;
END IF;
   EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BBANK_MANAGEMENT_EMPLOYEE_PK ON BBANK_MANAGEMENT_EMPLOYEE(BMSEMPLOYEE_ID) '; 

totalno := null;
  
SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BLOODBANK';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BLOODBANK CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BLOODBANK
    (BLOODBANK_ID NUMBER(10,0), 
	BLOODBANK_NAME VARCHAR2(40 BYTE) , 
	LOCATION_ID NUMBER(10,0)
   )';
   ELSE IF (totalno = 0) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BLOODBANK
    (BLOODBANK_ID NUMBER(10,0), 
	BLOODBANK_NAME VARCHAR2(40 BYTE) , 
	LOCATION_ID NUMBER(10,0)
   )';
END IF;
END IF;
   EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BLOODBANK_PK ON BLOODBANK (BLOODBANK_ID)'; 
   
 ---DECLARE BLOODGROUP
  totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BLOODGROUP';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BLOODGROUP  CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BLOODGROUP  
   (	"BLOODGROUP_ID" NUMBER(10,0), 
	"BLOODGROUP_NAME" VARCHAR2(40 BYTE) 
   )  ';
   ELSE IF (totalno = 0) THEN
   EXECUTE IMMEDIATE 'CREATE TABLE BLOODGROUP 
   (	"BLOODGROUP_ID" NUMBER(10,0), 
	"BLOODGROUP_NAME" VARCHAR2(40 BYTE) 
   )  ';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BLOODGROUP_PK ON BLOODGROUP(BLOODGROUP_ID)';
    
 
---DECLARE  totalno  NUMBER;

totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BLOODREQUEST';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BLOODREQUEST CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BLOODREQUEST
    (BLOODREQ_ID NUMBER(10,0), 
	HOSPITAL_ID NUMBER(10,0), 
	PATIENT_ID NUMBER(10,0), 
	REQSTATUSNO NUMBER(10,0),
    BLOODGROUP_ID NUMBER(10,0),
	QTYREQ NUMBER(10,0), 
	REQUESTDATE DATE, 
	REQPRIORITY VARCHAR2(40 BYTE) , 
	BMSEMPLOYEE_ID NUMBER(10,0)
   )';
    ELSE IF (totalno = 0) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BLOODREQUEST
    (BLOODREQ_ID NUMBER(10,0), 
	HOSPITAL_ID NUMBER(10,0), 
	PATIENT_ID NUMBER(10,0), 
	REQSTATUSNO NUMBER(10,0),
    BLOODGROUP_ID NUMBER(10,0),
	QTYREQ NUMBER(10,0), 
	REQUESTDATE DATE, 
	REQPRIORITY VARCHAR2(40 BYTE) , 
	BMSEMPLOYEE_ID NUMBER(10,0)
   )';
END IF;
END IF;
   EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BLOODREQUEST_PK ON BLOODREQUEST (BLOODREQ_ID)'; 
 

-----DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BLOOD_MANAGEMENT_SYSINVENTORY';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BLOOD_MANAGEMENT_SYSINVENTORY CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BLOOD_MANAGEMENT_SYSINVENTORY
    (BLOODINVENTORY_ID NUMBER(10,0), 
	BLOODTYPE VARCHAR2(40 BYTE) , 
	QTY NUMBER(10,0), 
	SAMPLINGDATE DATE, 
	SAMPLE_ID NUMBER(10,0), 
	DONOR_ID NUMBER(10,0)
   )';
    ELSE IF (totalno = 0) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BLOOD_MANAGEMENT_SYSINVENTORY
    (BLOODINVENTORY_ID NUMBER(10,0), 
	BLOODTYPE VARCHAR2(40 BYTE) , 
	QTY NUMBER(10,0), 
	SAMPLINGDATE DATE, 
	SAMPLE_ID NUMBER(10,0), 
	DONOR_ID NUMBER(10,0)
   )';
END IF;
END IF;
   EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BLOOD_MANAGEMENT_SYSINVENTORY_PK ON BLOOD_MANAGEMENT_SYSINVENTORY (BLOODINVENTORY_ID)';



------DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BMS_DOCTORS';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BMS_DOCTORS CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BMS_DOCTORS 
   (DOCTOR_ID NUMBER(10,0), 
	DOCTOR_NAME VARCHAR2(40 BYTE)
   ) ';
       ELSE IF (totalno = 0) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BMS_DOCTORS 
   (DOCTOR_ID NUMBER(10,0), 
	DOCTOR_NAME VARCHAR2(40 BYTE)
   ) ';
END IF;
END IF;
   EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BMS_DOCTORS_PK ON BMS_DOCTORS (DOCTOR_ID)';
  


-------DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'DONORDETAILS';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE DONORDETAILS CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE DONORDETAILS 
   (	DONOR_ID NUMBER(10,0),
	DONOR_NAME VARCHAR2(40 BYTE) , 
	DONOR_AGE NUMBER(10,0), 
	DONOR_PHONENO LONG , 
	LASTDONATIONDATE DATE
   )';
    ELSE IF (totalno = 0) THEN
      EXECUTE IMMEDIATE 'CREATE TABLE DONORDETAILS 
   (	DONOR_ID NUMBER(10,0),
	DONOR_NAME VARCHAR2(40 BYTE) , 
	DONOR_AGE NUMBER(10,0), 
	DONOR_PHONENO LONG , 
	LASTDONATIONDATE DATE
   )';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DONORDETAILS_PK ON DONORDETAILS (DONOR_ID)';
      


---DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'HOSPITAL';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE HOSPITAL CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL 
   (	HOSPITAL_ID NUMBER(10,0), 
	HOSPITAL_NAME VARCHAR2(40 BYTE) , 
	LOCATION_ID NUMBER(10,0)
   )';
       ELSE IF (totalno = 0) THEN
      EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL 
   (	HOSPITAL_ID NUMBER(10,0), 
	HOSPITAL_NAME VARCHAR2(40 BYTE) , 
	LOCATION_ID NUMBER(10,0)
   )';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX HOSPITAL_PK ON HOSPITAL (HOSPITAL_ID)';
      


---DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'LOCATION';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE LOCATION CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE LOCATION 
   (	LOCATION_ID NUMBER(10,0), 
	LOCATION_NAME VARCHAR2(40 BYTE), 
	LOC_PINCODE NUMBER(10,0)
   )';
          ELSE IF (totalno = 0) THEN
     EXECUTE IMMEDIATE 'CREATE TABLE LOCATION 
   (	LOCATION_ID NUMBER(10,0), 
	LOCATION_NAME VARCHAR2(40 BYTE), 
	LOC_PINCODE NUMBER(10,0)
   )';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX LOCATION_PK ON LOCATION (LOCATION_ID)';
      


----DECLARE  totalno  NUMBER;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'PATIENT';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE PATIENT CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE PATIENT 
   (	PATIENT_ID NUMBER(10,0), 
	PATIENT_NAME VARCHAR2(40 BYTE), 
	MEDICAL_HISTORY VARCHAR2 (4000 BYTE)
   ) ';
  ELSE IF (totalno = 0) THEN
     EXECUTE IMMEDIATE 'CREATE TABLE PATIENT 
  (	PATIENT_ID NUMBER(10,0), 
	PATIENT_NAME VARCHAR2(40 BYTE), 
	MEDICAL_HISTORY VARCHAR2 (4000 BYTE)
   ) ';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PATIENT_PK ON PATIENT (PATIENT_ID)';
      


----DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'REQSTATUSTYPE';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE REQSTATUSTYPE CASCADE CONSTRAINTS ';
      EXECUTE IMMEDIATE 'CREATE TABLE REQSTATUSTYPE   
   (REQSTATUSNO NUMBER(10,0), 
	STATUSTYPE VARCHAR2(40 BYTE) 
   )';
   ELSE IF (totalno = 0) THEN
     EXECUTE IMMEDIATE 'CREATE TABLE REQSTATUSTYPE 
   (REQSTATUSNO NUMBER(10,0), 
	STATUSTYPE VARCHAR2(40 BYTE) 
   )';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX REQSTATUSTYPE_PK ON REQSTATUSTYPE (REQSTATUSNO)';
      


-----DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'SAMPLECHECKDETAILS';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE SAMPLECHECKDETAILS CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE SAMPLECHECKDETAILS 
   (	SCD_ID NUMBER(10,0), 
	SAMPLE_ID NUMBER(10,0), 
	DOCTOR_ID NUMBER(10,0), 
	RESULT VARCHAR2(40 BYTE) 
   ) ';
   ELSE IF (totalno = 0) THEN
     EXECUTE IMMEDIATE 'CREATE TABLE SAMPLECHECKDETAILS 
   (	SCD_ID NUMBER(10,0), 
	SAMPLE_ID NUMBER(10,0), 
	DOCTOR_ID NUMBER(10,0), 
	RESULT VARCHAR2(40 BYTE) 
   ) ';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SAMPLECHECKDETAILS_PK ON SAMPLECHECKDETAILS(SCD_ID)';
 
/* 
 totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'BLOODGROUP';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE BLOODGROUP  CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE BLOODGROUP  
   (	"BLOODGROUP_ID" NUMBER(10,0), 
	"BLOODGROUP_NAME" VARCHAR2(40 BYTE) 
   )  ';
   ELSE IF (totalno = 0) THEN
   EXECUTE IMMEDIATE 'CREATE TABLE BLOODGROUP 
   (	"BLOODGROUP_ID" NUMBER(10,0), 
	"BLOODGROUP_NAME" VARCHAR2(40 BYTE) 
   )  ';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX BLOODGROUP_PK ON BLOODGROUP(BLOODGROUP_ID)';
    
*/

-----DECLARE  totalno  NUMBER;
totalno:=null;
  
  SELECT count(*) INTO totalno FROM user_tables WHERE table_name = 'SAMPLEDETAILS';
  IF totalno > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABlE  SAMPLEDETAILS CASCADE CONSTRAINTS';
      EXECUTE IMMEDIATE 'CREATE TABLE SAMPLEDETAILS 
   (	SAMPLE_ID NUMBER(10,0), 
	DONOR_ID NUMBER(10,0), 
	SAMPLINGDATE DATE, 
	BLOODTYPE VARCHAR2(40 BYTE), 
	QTY NUMBER(10,0)
   )';
    ELSE IF (totalno = 0) THEN
     EXECUTE IMMEDIATE 'CREATE TABLE SAMPLEDETAILS 
   (	SAMPLE_ID NUMBER(10,0), 
	DONOR_ID NUMBER(10,0), 
	SAMPLINGDATE DATE, 
	BLOODTYPE VARCHAR2(40 BYTE), 
	QTY NUMBER(10,0)
   )';
END IF;
END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SAMPLEDETAILS_PK ON SAMPLEDETAILS (SAMPLE_ID)';
      
END;

